# Generated by Django 5.0.6 on 2024-05-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Országok',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attractions.countries')),
            ],
            options={
                'verbose_name_plural': 'Városok',
            },
        ),
        migrations.CreateModel(
            name='TourismAttractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('average_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('opening_hours', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attractions.cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attractions.countries')),
            ],
            options={
                'verbose_name_plural': 'Turisztikai Látványosságok',
            },
        ),
    ]
