# Generated by Django 5.0.6 on 2024-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='country',
        ),
    ]
