# Generated by Django 5.0.6 on 2024-05-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attractions', '0002_remove_cities_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismattractions',
            name='country',
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Attractions.countries'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
