# Generated by Django 5.0.6 on 2024-05-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attractions', '0003_remove_tourismattractions_country_cities_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
