# Generated by Django 5.0.3 on 2024-03-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szakNev', models.CharField(max_length=200)),
                ('tamogatott', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Felvetelizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('szul_ev', models.DateField()),
                ('pontszam', models.IntegerField()),
                ('szak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felviadmin.szak')),
            ],
        ),
    ]
