# Generated by Django 5.0.3 on 2024-03-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('felviadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szak',
            name='tamogatott',
        ),
    ]
