# Generated by Django 5.0.3 on 2024-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felviadmin', '0002_remove_szak_tamogatott'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felvetelizo',
            name='szul_ev',
            field=models.IntegerField(),
        ),
    ]
