# Generated by Django 5.0.3 on 2024-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felviadmin', '0003_alter_felvetelizo_szul_ev'),
    ]

    operations = [
        migrations.AddField(
            model_name='felvetelizo',
            name='felvetelizo_id',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='szak',
            name='szak_id',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
