# Generated by Django 5.0.3 on 2024-03-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('felviadmin', '0004_felvetelizo_felvetelizo_id_szak_szak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='felvetelizo',
            name='felvetelizo_id',
        ),
        migrations.RemoveField(
            model_name='szak',
            name='szak_id',
        ),
    ]
