# Generated by Django 5.0.6 on 2024-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varos', models.CharField(max_length=100)),
                ('utca', models.CharField(default='X', max_length=100)),
                ('ertek', models.FloatField()),
                ('idopont', models.DateTimeField()),
            ],
        ),
    ]
