# Generated by Django 5.0.2 on 2024-02-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriaNev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termekNev', models.CharField(max_length=100)),
                ('ar', models.IntegerField()),
                ('db', models.IntegerField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raktar.kategoria')),
            ],
        ),
    ]
